version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - /Volumes/DEV/volumes_docker/databases/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack:latest
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass root
    volumes:
      - /Volumes/DEV/volumes_docker/databases/redis:/data
      - /path/to/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: root
    ports:
      - "6379:6379"


